Standardize README across raw BIDS subdatasets
courtois-neuromod/bids_template pull request #1
Opened 2022-04-05 01:14 UTC by bpinsard

Started to write a template for basic infos (and mainly links to centralized doc) that would be available in the BIDS readme.
What else should we included here?
- Authors?
- Contacts?
- Link to DTA (docs).
- License?

2022-04-05 14:33 UTC, pbellec requested changes

2022-04-05 14:33 UTC, pbellec commented on README
> +It contains:
suggestion: merge "This subdataset contains (...)" with "It contains".

2022-04-05 14:33 UTC, pbellec commented on README
> +- physiological data
Suggestion: add author and access information. 

This dataset was designed by XX, with input from XX, XX. The subdataset was collected  by XX, XX. Further improvements on data organization as well as quality control have been implemented by XX, XX. This subdataset also benefited from resources assembled by the entire [Courtois NeuroMod team](https://docs.cneuromod.ca/en/latest/AUTHORS.html).

Courtois NeuroMod data are freely shared with the scientific community to advance research at the interface of neuroscience and artificial intelligence. Access to to the data is based on a registered access model, see the [Courtois NeuroMod website](https://docs.cneuromod.ca/en/latest/ACCESS.html) for more information. Redistribution of data outside of the Courtois NeuroMod data bank is prohibited.

2022-04-05 14:33 UTC, pbellec commented on README
> +# CNeuromod: [xxxx subdataset](https://github.com/courtois-neuromod/xxxxx)
We are using two abbreviations: cneuromod (short) and Courtois NeuroMod (long). I suggest to stick to Courtois NeuroMod here.

2022-04-05 14:33 UTC, pbellec commented on README
> +This BIDS dataset is part of the [Courtois-Neuromod dataset](https://docs.cneuromod.ca/).
See my comment above Courtois-Neuromod -> Courtois NeuroMod

2022-04-05 14:33 UTC, pbellec commented on README
> +This BIDS dataset is part of the [Courtois-Neuromod dataset](https://docs.cneuromod.ca/).
I would also remove the reference to BIDS from this sentence. Some of our subdataset will be BIDS-like, but not strictly BIDS compliant.

2022-04-05 14:33 UTC, pbellec commented on README
> +
I would add a sentence here on BIDS. 

OPTIONAL: 

This subdataset is organized following the [brain imaging data structure](https://bids.neuroimaging.io/).
OR
This subdataset is organized following principles which mimic the [brain imaging data structure](https://bids.neuroimaging.io/), but it does not conform to an established standard.

2022-04-05 14:33 UTC, pbellec commented on README
I would add a general intro to the project:

The Courtois project on Neural Modelling ([Courtois NeuroMod](https://cneuromod.ca)) aims at training artificial neural networks using extensive experimental data on individual human brain activity and behaviour.

2022-04-05 14:35 UTC, lunebellec commented
Thanks for getting this started Basile! 

I am not sure what to do with the failed bids validator test. Could we add some minimal common folder structure so that the test passes?

2022-04-05 17:06 UTC, bpinsard commented
> Thanks for getting this started Basile!

Thanks for your helpful comments. 
> I am not sure what to do with the failed bids validator test. Could we add some minimal common folder structure so that the test passes?

Creating a fake BIDS would require removing it when applying the template. 
I guess we could just add a condition that would skip it on this template (by detecting the git url), will look into that option.

2022-05-09 17:24 UTC, bpinsard commented
@pbellec @julieaboyle1 are we ok with the latest version. I would like to apply that README to all existing datasets for the release. Thanks

2022-05-24 14:40 UTC, pbellec approved these changes

2022-05-24 14:41 UTC, pbellec commented
Looking great! Thanks @bpinsard !

2022-05-24 15:11 UTC, merged